apiVersion: v1
kind: Service
metadata:
  name: incident-analyzer-service
spec:
  type: NodePort
  selector:
    app: incident-analyzer
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007